apiVersion: oracle.iwhalecloud.com/v1
kind: OracleCluster
metadata:
  name: oraclecluster-sample
spec:
  image: 10.10.236.107:8099/k8s/oracle/container-registry.oracle.com/database/enterprise:19.3.0.0
  cliImage: 10.10.236.107:8099/oracle/instantclient:19-gotty-3
  replicas: 1
  password: enRlc29mdA==
  podSpec:
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 8
        memory: 8192Mi
      requests:
        cpu: 1
        memory: 1024Mi
  volumeSpec:
    persistentVolumeClaim:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "100Gi"
      storageClassName: "dise-default"
